networks:
  dev-network:
    driver: bridge

services:
  dev-db:
    image: postgres:17.4-alpine3.21
    restart: always
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d:z
    networks:
      - dev-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - dev-network

name: fastapi-development